sudo: required
services:
  - docker

before_install:
  - docker build -t dockercristina/docker-react -f Dockerfile.dev . 

script:
  - docker run dockercristina/docker-react npm run test -- --coverage